name: flutter_kamusku
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.4.1
  firebase_auth: 4.2.4
  cloud_firestore: 4.3.1
  dio: ^4.0.0
  textfield_search: ^0.10.0 
  flutter_screenutil: ^5.6.0
  carousel_slider: ^4.2.1
  google_fonts: ^2.1.0
  get_storage: any
  sembast: any
  sembast_web: any
  uuid: ^3.0.7
  audioplayers: any
  lottie: any

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

